export const Users = [
  {
    id:1,
    profilePicture: "https://f.hellowork.com/blogdumoderateur/2013/02/nyan-cat-gif-1.gif",
    username: "une fille",
  },
  {
    id:2,
    profilePicture: "https://c.tenor.com/zsP0bShJ5PsAAAAC/snk.gif",
    username: "moi",
  },
  {
    id:3,
    profilePicture: "https://c.tenor.com/eeCV7mbY4l0AAAAC/nicky-larson.gif",
    username: "Dora",
  },
  {
    id:4,
    profilePicture: "https://i.pinimg.com/originals/b7/ff/d8/b7ffd803720bdd628ed684200acc4c71.gif",
    username: "zoupzoup",
  },
  {
    id:5,
    profilePicture: "https://i.pinimg.com/originals/f8/09/4e/f8094eda649d60e5a15c27252f88f8e6.gif",
    username: "thomas",
  },
  {
    id:6,
    profilePicture: "https://thumbs.gfycat.com/DifferentImpureBorderterrier-size_restricted.gif",
    username: "Shirley",
  },
  {
    id:7,
    profilePicture: "https://www.jedecore.com/gif/alien/alien-danse-001.gif",
    username: "Travis ",
  },
  {
    id:8,
    profilePicture: "https://www.jedecore.com/gif/alien/alien-003.gif",
    username: " Thomas a",
  },
  {
    id:9,
    profilePicture: "http://mykomet.fr/img/e8nZC.gif",
    username: "Gary ",
  },
  {
    id:10,
    profilePicture: "https://thumbs.gfycat.com/BadDifficultHaddock-size_restricted.gif",
    username: "sonic",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Trop cool  ",
    photo: "https://f.hellowork.com/blogdumoderateur/2013/02/nyan-cat-gif-1.gif",
    date: "il y a 5min",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "htpps://c.tenor.com/zsP0bShJ5PsAAAAC/snk.gif",
    date: "il y a 15min",
    desc: "Trop cool une bouteille  ",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Trop cool une bouteille",
    photo: "https://c.tenor.com/eeCV7mbY4l0AAAAC/nicky-larson.gif",
    date: "il y a 1 heure",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Trop cool une bouteille",
    photo: "https://i.pinimg.com/originals/b7/ff/d8/b7ffd803720bdd628ed684200acc4c71.gif",
    date: "il ya 4 heures",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "https://i.pinimg.com/originals/f8/09/4e/f8094eda649d60e5a15c27252f88f8e6.gif",
    date: "il y a 5 heures",
    userId: 5,
    desc: "Trop cool une bouteille",
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "https://thumbs.gfycat.com/DifferentImpureBorderterrier-size_restricted.gif",
    date: "il y a 1 jour",
    desc: "Trop cool une bouteille",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Trop cool une bouteille",
    photo: "https://www.jedecore.com/gif/alien/alien-danse-001.gif",
    date: "il y a 2 jours",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "https://www.jedecore.com/gif/alien/alien-003.gif",
    date: "IL Y A 3 JOURS ",
    desc: "Trop cool une bouteille",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Trop cool une bouteille",
    photo: "http://mykomet.fr/img/e8nZC.gif",
    date: "IL Y A 5 JOURS",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "https://thumbs.gfycat.com/BadDifficultHaddock-size_restricted.gif",
    date: "IL Y A UN WEED END !!!",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
