export const Users = [
  {
    id:1,
    profilePicture: "https://f.hellowork.com/blogdumoderateur/2013/02/nyan-cat-gif-1.gif",
    username: "une fille",
  },
  {
    id:2,
    profilePicture: "https://c.tenor.com/zsP0bShJ5PsAAAAC/snk.gif",
    username: "moi",
  },
  {
    id:3,
    profilePicture: "https://c.tenor.com/eeCV7mbY4l0AAAAC/nicky-larson.gif",
    username: "Dora",
  },
  {
    id:4,
    profilePicture: "https://i.pinimg.com/originals/b7/ff/d8/b7ffd803720bdd628ed684200acc4c71.gif",
    username: "zoupzoup",
  },
  {
    id:5,
    profilePicture: "https://i.pinimg.com/originals/f8/09/4e/f8094eda649d60e5a15c27252f88f8e6.gif",
    username: "thomas",
  },
  {
    id:6,
    profilePicture: "https://thumbs.gfycat.com/DifferentImpureBorderterrier-size_restricted.gif",
    username: "Shirley",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Travis ",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: " Thomas a",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Gary ",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "sonic",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
